### ISSUE TITLE
Collision & Gravity

### ISSUE THREAD

**Issue by Yhac10** [Piercin/Gdevelop3DPhysics#1]
I would like to make a suggestions for two features.

1. Collision
There should be an option to add collision to an object. I have tried ways to implement collision through Gdevelop itself, but my solutions mostly ended up with no collision, so it would be nice for a built in collision function.
2. Gravity
Although the fall function is similar, I think having it just be gravity make things be so much easier for devs. You could make it as an event, or do something similar to the platformer extension, and make it run automatically, with adjustable parameters.

**Comment by Piercin** [comment]
Hello,

What exactly do you mean by collision? If you want the player separated from blocks, there are three actions necessary for it. Heres a video that shows the order of necessary events [https://youtu.be/ojr4rGfdPJA?si=WuuAc8c7tmpZJseu](here)

Or if you mean a condition that detects if the player is in collision with a 3d object, it's called "Detect 3d collision"


How is falling any different? What would gravity do?

**Comment by Yhac10** [comment]
Okay, I implemented the collision into my project, however, it seems that the 3D top separate event isn't working for me.
Here's the code I'm using.
![image](https://github.com/Piercin/Gdevelop3DPhysics/assets/97116565/faeb2645-5d98-4f1c-9e92-5328e0f8b245)
I'm not sure if it's an issue with the size of the floor being one 3D pixel in depth, or if I made a mistake in the event sheet.

**Comment by Piercin** [comment]
> Okay, I implemented the collision into my project, however, it seems that the 3D top separate event isn't working for me.
> Here's the code I'm using.
> ![image](https://github.com/Piercin/Gdevelop3DPhysics/assets/97116565/faeb2645-5d98-4f1c-9e92-5328e0f8b245)
> I'm not sure if it's an issue with the size of the floor being one 3D pixel in depth, or if I made a mistake in the event sheet.

Gotta put the event in "repeat for each object", otherwise it just chooses one object in the scene.

Can you still explain to me what you meant by gravity? Why doesnt falling work?

**Comment by Yhac10** [comment]
Okay, thanks for the information.
As for gravity, back when I made the comment, my code didn't work well, so the falling was of to me. That's a mistake on my end.
Either that or I felt that gravity was just a better name.

**Comment by Piercin** [comment]
> Collision still doesn't seem to work for me.
> Here are the events I'm using
> ![image](https://github.com/Piercin/Gdevelop3DPhysics/assets/97116565/af89e973-b9b4-4408-8308-fc68d2ccae79)
> 

Maybe it's because your not using the group objects on 2d separation?

**Comment by Yhac10** [comment]
Tried it, still fell through the floor.

Maybe it has something to do with the level layout it self.
here's a snippet of the level layout from Gdevelop
![image](https://github.com/Piercin/Gdevelop3DPhysics/assets/97116565/5377502f-b44f-4c9c-8d1f-c510ec5cc4b3)

**Comment by Piercin** [comment]
Does it fall everywhere? Show me the values of the behavior

**Comment by Piercin** [comment]
Alright, i think i know the problem (hopefully) 

Edit the behavior of your camera and change the "Pickup range of obstacle" value to double your falling speed.

its the range that the player gets sent to the bottom  of the cube, so if the value isn't about double the falling speed it'll basically just fall right through.

I hope that helps.

**Comment by Yhac10** [comment]
It worked great. It for some reason had a bug where I would fall through the floor once touching A wall, but I managed to fix that pretty easily. Thanks for the help.
