### ISSUE TITLE
Camera Falling Bug

### ISSUE THREAD

**Issue by Yhac10** [Piercin/Gdevelop3DPhysics#2]
I think I found a bug.
While testing movement, I found that if I moved my camera to a certain position, while the player was touching a wall, the player will fall through the floor.
I tried fixing it by increasing pickup range, but that didn't seem to work (I set pickup range to 16, with fall speed being 4).

**Comment by Piercin** [comment]
sometimes happens when cubes are at certain positions, can you show where it happens ?

**Comment by Yhac10** [comment]
Whole Map
![image](https://github.com/Piercin/Gdevelop3DPhysics/assets/97116565/11635bf3-d0a5-4819-bf51-835fd5804196)
Part's where bug happened
![image](https://github.com/Piercin/Gdevelop3DPhysics/assets/97116565/846741d4-0350-4aa7-8e9e-609df5e877cf)
![image](https://github.com/Piercin/Gdevelop3DPhysics/assets/97116565/e2d2a920-47df-4bd2-ab6a-8526aef29dec)

**Comment by Piercin** [comment]
Show a video of it happening?

**Comment by Piercin** [comment]
Show a video of it happening?

**Comment by Yhac10** [comment]
sure

**Comment by Yhac10** [comment]
I could be wrong about the player falling through the floor, as all that happens is that the player go's somewhere with no sign of floor, or wall.

**Comment by Piercin** [comment]
Weird. Can you try to get a text and set the text to the z of your player? Then see if it's going up or down

**Comment by Yhac10** [comment]
I checked using the debugger. At the start of the scene the Z position of the player was 1. When the glitch happened, it was -656.

**Comment by Piercin** [comment]
Alright that's odd. Can you show me all the events regarding the extension?

**Comment by Yhac10** [comment]
Okay.
![image](https://github.com/Piercin/Gdevelop3DPhysics/assets/97116565/1f414ed3-578f-4f63-9861-d34c2fc4ce80)

**Comment by Piercin** [comment]
I think you could put the pickup value at 8. And if that doesn't change anything, im gonna do a rework to the extension

**Comment by Yhac10** [comment]
Tried it, and nothing changed. Although now I can confirm that the player falls as after refreshing the debugger multiple times, the Z position would decrease more and more.

**Comment by Yhac10** [comment]
Maybe it could have something to do with the position of the wall

**Comment by Yhac10** [comment]
Ok, after doing some testing, I found out the glitch happens when you touch a corner.

**Comment by Piercin** [comment]
I see, weird things might happen depending on the angle of the player. I just change the cameras angle by itself.

**Comment by Yhac10** [comment]
Ok. Thanks for the advice.

**Comment by Piercin** [comment]
No problem, ima need to fix that glitch though. Since it shouldn't happen, so im gonna have to rework the events to make it better.
