### ISSUE TITLE
weird issue originally reported by @Yhac10

### ISSUE THREAD

**Issue by Piercin** [Piercin/Gdevelop3DPhysics#3]
@Yhac10 have you tried the newest version yet? does that glitch still happen?

**Comment by Yhac10** [comment]
Not yet, Imma try it now.

**Comment by Yhac10** [comment]
Ok, tried it, and for me, there seems to be a new bug. When I touch the wall, I get sent to the top of it, before falling.

**Comment by Yhac10** [comment]
Also, what's behaviour2?

**Comment by Yhac10** [comment]
?

**Comment by Yhac10** [comment]
Ok, collision is working fine, no glitch, however, for some reason I can't jump. Can you please send a screenshot of working jump code please?

**Comment by Piercin** [comment]
this tutorial has the code https://youtu.be/6oDxo0AZb0Q?si=zBwPqCCmr7BEE2JC

**Comment by Yhac10** [comment]
Ok, got it.
